# Generated by Django 2.0.4 on 2018-05-31 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_orderinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consignment_type', models.CharField(choices=[('vendor', '供应商发货'), ('customer', '客户发货')], default='customer', max_length=10, verbose_name='包裹类型')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('sum_in_rmb', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='人民币总费用')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='重量(KG)')),
            ],
            options={
                'verbose_name': '发货包裹',
                'verbose_name_plural': '发货包裹',
                'db_table': 'consignment',
            },
        ),
        migrations.CreateModel(
            name='Inquery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('vendor', '向供应商询价'), ('customer', '客户询价')], default='customer', max_length=10, verbose_name='询价类型')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='付款日期')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Partner', verbose_name='合作伙伴')),
            ],
            options={
                'verbose_name': '询价',
                'verbose_name_plural': '询价',
                'db_table': 'inquery',
            },
        ),
        migrations.CreateModel(
            name='InqueryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='单位数量')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='总价')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('inquery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Inquery', verbose_name='询价')),
                ('product_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ProductHasPrice', verbose_name='单位价格')),
            ],
            options={
                'verbose_name': '询价条目',
                'verbose_name_plural': '询价条目',
                'db_table': 'inquery_item',
            },
        ),
        migrations.CreateModel(
            name='LogisticVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='物流商名称')),
                ('contact', models.TextField(blank=True, null=True, verbose_name='联系方式')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '物流商',
                'verbose_name_plural': '物流商',
                'db_table': 'logistic_vendor',
            },
        ),
        migrations.CreateModel(
            name='OrderConsignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Consignment', verbose_name='包裹')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单包裹',
                'verbose_name_plural': '订单包裹',
                'db_table': 'order_consignment',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='partner',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='logistic_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.LogisticVendor', verbose_name='物流商'),
        ),
    ]
