# Generated by Django 2.0.4 on 2018-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180917_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.IntegerField(default=1, verbose_name='最小起订量'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='包装量'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', max_length=100, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(choices=[('list_price', '面价'), ('net', '折后价'), ('other', '其他')], max_length=20, verbose_name='价格种类'),
        ),
    ]
