# Generated by Django 2.0.4 on 2018-10-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181013_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthasprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='producthasprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inqueryitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_price',
        ),
        migrations.AddField(
            model_name='inqueryitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='inqueryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='单位价格'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='单位价格'),
        ),
        migrations.AddField(
            model_name='product',
            name='euro_list_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, verbose_name='欧元面价'),
        ),
        migrations.AddField(
            model_name='product',
            name='euro_net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='欧元折后价'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ProductHasPrice',
        ),
    ]
